controllers:
    resource: ../src/Controller/
    type: annotation
    prefix:
        nl: ''
        en: '/en'
    trailing_slash_on_root: false
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locales: '%locale%'

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_logout:
    path: /logout
    methods: GET

redirect:
    path: /
    controller: App\Controller\RedirectController::redirectToLocale
